name: CI

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hl7fhir/ig-publisher-base:latest
    steps:
      - name: clone scripts 
        run: gosu publisher git clone https://github.com/HL7/ig-publisher-scripts.git /home/publisher/bin
      - name: update publisher
        run: gosu publisher _updatePublisher.sh -y
      - name: Run pwd on scripts directory 
        run: pwd
      - name: Run ls on scripts directory 
        run: ls 
      - name: Run ls on publisher directory 
        run: ls /home/publisher/bin
        
      - name: Checkout ./core
        uses: actions/checkout@v2
        with:
          path: core
      - name: Run ls on scripts directory 
        run: ls 
      - name: Run publisher command
        run: java -jar ./input-cache/publisher.jar publisher -ig core
